image: mcr.microsoft.com/dotnet/sdk:6.0

variables:
  GIT_DEPTH: 10
  GIT_SSL_NO_VERIFY: "true"

stages:
  - build
  - test
  - deploy

job_build:
  stage: build
  tags:
    - estg
  script:
    - dotnet build

job_test:
  stage: test
  tags:
    - estg
  script:
    - dotnet test

job_deploy:
  stage: deploy
  tags:
    - estg
  only:
    - master
  artifacts:
    paths:
      - publish/
  script:
    - dotnet publish -c Release -o ./publish  backend_sportsintime/backend_sportsintime.csproj
